// Mocks generated by Mockito 5.4.4 from annotations
// in pixelodon/test/features/settings/settings_screen_scaffold_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i3;

import 'package:flutter/material.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:pixelodon/models/account.dart' as _i6;
import 'package:pixelodon/models/instance.dart' as _i2;
import 'package:pixelodon/repositories/auth_repository.dart' as _i4;
import 'package:pixelodon/services/settings_service.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeInstance_0 extends _i1.SmartFake implements _i2.Instance {
  _FakeInstance_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocale_1 extends _i1.SmartFake implements _i3.Locale {
  _FakeLocale_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Instance> get instances => (super.noSuchMethod(
        Invocation.getter(#instances),
        returnValue: <_i2.Instance>[],
      ) as List<_i2.Instance>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void setActiveInstance(String? domain) => super.noSuchMethod(
        Invocation.method(
          #setActiveInstance,
          [domain],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i2.Instance> discoverInstance(String? domain) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverInstance,
          [domain],
        ),
        returnValue: _i5.Future<_i2.Instance>.value(_FakeInstance_0(
          this,
          Invocation.method(
            #discoverInstance,
            [domain],
          ),
        )),
      ) as _i5.Future<_i2.Instance>);

  @override
  _i5.Future<Map<String, String>> startOAuthFlow(
    String? domain, {
    bool? forRegistration = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startOAuthFlow,
          [domain],
          {#forRegistration: forRegistration},
        ),
        returnValue: _i5.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i5.Future<Map<String, String>>);

  @override
  _i5.Future<bool> completeOAuthFlow(
    String? domain,
    String? code, {
    String? state,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeOAuthFlow,
          [
            domain,
            code,
          ],
          {#state: state},
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> refreshAccessToken(String? domain) => (super.noSuchMethod(
        Invocation.method(
          #refreshAccessToken,
          [domain],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> logout(String? domain) => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [domain],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isAuthenticated(String? domain) => (super.noSuchMethod(
        Invocation.method(
          #isAuthenticated,
          [domain],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<String?> getAccessToken(String? domain) => (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [domain],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<bool> validateAccessToken(String? domain) => (super.noSuchMethod(
        Invocation.method(
          #validateAccessToken,
          [domain],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> updateAccountInfo(String? domain) => (super.noSuchMethod(
        Invocation.method(
          #updateAccountInfo,
          [domain],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i6.Account? getAccount(String? domain) =>
      (super.noSuchMethod(Invocation.method(
        #getAccount,
        [domain],
      )) as _i6.Account?);

  @override
  void addListener(_i3.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i7.SettingsService {
  MockSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i8.ThemeMode> getThemeMode() => (super.noSuchMethod(
        Invocation.method(
          #getThemeMode,
          [],
        ),
        returnValue: _i5.Future<_i8.ThemeMode>.value(_i8.ThemeMode.system),
      ) as _i5.Future<_i8.ThemeMode>);

  @override
  _i5.Future<void> setThemeMode(_i8.ThemeMode? themeMode) =>
      (super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [themeMode],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.Locale> getLanguage() => (super.noSuchMethod(
        Invocation.method(
          #getLanguage,
          [],
        ),
        returnValue: _i5.Future<_i3.Locale>.value(_FakeLocale_1(
          this,
          Invocation.method(
            #getLanguage,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Locale>);

  @override
  _i5.Future<void> setLanguage(_i3.Locale? locale) => (super.noSuchMethod(
        Invocation.method(
          #setLanguage,
          [locale],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, bool>> getNotificationSettings() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotificationSettings,
          [],
        ),
        returnValue: _i5.Future<Map<String, bool>>.value(<String, bool>{}),
      ) as _i5.Future<Map<String, bool>>);

  @override
  _i5.Future<void> setNotificationSettings(Map<String, bool>? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNotificationSettings,
          [settings],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> getOnboardingCompleted() => (super.noSuchMethod(
        Invocation.method(
          #getOnboardingCompleted,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setOnboardingCompleted(bool? completed) =>
      (super.noSuchMethod(
        Invocation.method(
          #setOnboardingCompleted,
          [completed],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>?> getOnboardingPreferences() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOnboardingPreferences,
          [],
        ),
        returnValue: _i5.Future<Map<String, dynamic>?>.value(),
      ) as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<void> setOnboardingPreferences(
          Map<String, dynamic>? preferences) =>
      (super.noSuchMethod(
        Invocation.method(
          #setOnboardingPreferences,
          [preferences],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resetOnboarding() => (super.noSuchMethod(
        Invocation.method(
          #resetOnboarding,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearAllSettings() => (super.noSuchMethod(
        Invocation.method(
          #clearAllSettings,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<_i8.ThemeMode> getAvailableThemeModes() => (super.noSuchMethod(
        Invocation.method(
          #getAvailableThemeModes,
          [],
        ),
        returnValue: <_i8.ThemeMode>[],
      ) as List<_i8.ThemeMode>);

  @override
  List<_i3.Locale> getAvailableLanguages() => (super.noSuchMethod(
        Invocation.method(
          #getAvailableLanguages,
          [],
        ),
        returnValue: <_i3.Locale>[],
      ) as List<_i3.Locale>);

  @override
  String getLanguageDisplayName(_i3.Locale? locale) => (super.noSuchMethod(
        Invocation.method(
          #getLanguageDisplayName,
          [locale],
        ),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.method(
            #getLanguageDisplayName,
            [locale],
          ),
        ),
      ) as String);

  @override
  String getThemeModeDisplayName(_i8.ThemeMode? themeMode) =>
      (super.noSuchMethod(
        Invocation.method(
          #getThemeModeDisplayName,
          [themeMode],
        ),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.method(
            #getThemeModeDisplayName,
            [themeMode],
          ),
        ),
      ) as String);
}
