// Mocks generated by Mockito 5.4.4 from annotations
// in pixelodon/test/features/profile/data/profile_sources_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dio/dio.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pixelodon/models/account.dart' as _i2;
import 'package:pixelodon/models/paginated_result.dart' as _i3;
import 'package:pixelodon/models/status.dart' as _i4;
import 'package:pixelodon/services/account_service.dart' as _i5;
import 'package:pixelodon/services/timeline_service.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAccount_0 extends _i1.SmartFake implements _i2.Account {
  _FakeAccount_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaginatedResult_1<T> extends _i1.SmartFake
    implements _i3.PaginatedResult<T> {
  _FakePaginatedResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStatus_2 extends _i1.SmartFake implements _i4.Status {
  _FakeStatus_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AccountService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountService extends _i1.Mock implements _i5.AccountService {
  MockAccountService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Account> getVerifyCredentials(String? domain) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVerifyCredentials,
          [domain],
        ),
        returnValue: _i6.Future<_i2.Account>.value(_FakeAccount_0(
          this,
          Invocation.method(
            #getVerifyCredentials,
            [domain],
          ),
        )),
      ) as _i6.Future<_i2.Account>);

  @override
  _i6.Future<_i2.Account> getAccount(
    String? domain,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccount,
          [
            domain,
            id,
          ],
        ),
        returnValue: _i6.Future<_i2.Account>.value(_FakeAccount_0(
          this,
          Invocation.method(
            #getAccount,
            [
              domain,
              id,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Account>);

  @override
  _i6.Future<List<_i2.Account>> searchAccounts(
    String? domain, {
    required String? query,
    int? limit,
    bool? following,
    bool? resolve,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchAccounts,
          [domain],
          {
            #query: query,
            #limit: limit,
            #following: following,
            #resolve: resolve,
          },
        ),
        returnValue: _i6.Future<List<_i2.Account>>.value(<_i2.Account>[]),
      ) as _i6.Future<List<_i2.Account>>);

  @override
  _i6.Future<_i3.PaginatedResult<_i2.Account>> getFollowers(
    String? domain,
    String? id, {
    int? limit,
    String? maxId,
    String? sinceId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFollowers,
          [
            domain,
            id,
          ],
          {
            #limit: limit,
            #maxId: maxId,
            #sinceId: sinceId,
          },
        ),
        returnValue: _i6.Future<_i3.PaginatedResult<_i2.Account>>.value(
            _FakePaginatedResult_1<_i2.Account>(
          this,
          Invocation.method(
            #getFollowers,
            [
              domain,
              id,
            ],
            {
              #limit: limit,
              #maxId: maxId,
              #sinceId: sinceId,
            },
          ),
        )),
      ) as _i6.Future<_i3.PaginatedResult<_i2.Account>>);

  @override
  _i6.Future<_i3.PaginatedResult<_i2.Account>> getFollowing(
    String? domain,
    String? id, {
    int? limit,
    String? maxId,
    String? sinceId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFollowing,
          [
            domain,
            id,
          ],
          {
            #limit: limit,
            #maxId: maxId,
            #sinceId: sinceId,
          },
        ),
        returnValue: _i6.Future<_i3.PaginatedResult<_i2.Account>>.value(
            _FakePaginatedResult_1<_i2.Account>(
          this,
          Invocation.method(
            #getFollowing,
            [
              domain,
              id,
            ],
            {
              #limit: limit,
              #maxId: maxId,
              #sinceId: sinceId,
            },
          ),
        )),
      ) as _i6.Future<_i3.PaginatedResult<_i2.Account>>);

  @override
  _i6.Future<Map<String, dynamic>> getRelationship(
    String? domain,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRelationship,
          [
            domain,
            id,
          ],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<_i2.Account> followAccount(
    String? domain,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #followAccount,
          [
            domain,
            id,
          ],
        ),
        returnValue: _i6.Future<_i2.Account>.value(_FakeAccount_0(
          this,
          Invocation.method(
            #followAccount,
            [
              domain,
              id,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Account>);

  @override
  _i6.Future<_i2.Account> unfollowAccount(
    String? domain,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unfollowAccount,
          [
            domain,
            id,
          ],
        ),
        returnValue: _i6.Future<_i2.Account>.value(_FakeAccount_0(
          this,
          Invocation.method(
            #unfollowAccount,
            [
              domain,
              id,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Account>);

  @override
  _i6.Future<_i2.Account> blockAccount(
    String? domain,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #blockAccount,
          [
            domain,
            id,
          ],
        ),
        returnValue: _i6.Future<_i2.Account>.value(_FakeAccount_0(
          this,
          Invocation.method(
            #blockAccount,
            [
              domain,
              id,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Account>);

  @override
  _i6.Future<_i2.Account> unblockAccount(
    String? domain,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unblockAccount,
          [
            domain,
            id,
          ],
        ),
        returnValue: _i6.Future<_i2.Account>.value(_FakeAccount_0(
          this,
          Invocation.method(
            #unblockAccount,
            [
              domain,
              id,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Account>);

  @override
  _i6.Future<_i2.Account> muteAccount(
    String? domain,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #muteAccount,
          [
            domain,
            id,
          ],
        ),
        returnValue: _i6.Future<_i2.Account>.value(_FakeAccount_0(
          this,
          Invocation.method(
            #muteAccount,
            [
              domain,
              id,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Account>);

  @override
  _i6.Future<_i2.Account> unmuteAccount(
    String? domain,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unmuteAccount,
          [
            domain,
            id,
          ],
        ),
        returnValue: _i6.Future<_i2.Account>.value(_FakeAccount_0(
          this,
          Invocation.method(
            #unmuteAccount,
            [
              domain,
              id,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Account>);

  @override
  _i6.Future<_i2.Account> updateCredentials(
    String? domain, {
    String? displayName,
    String? note,
    String? avatar,
    String? header,
    bool? locked,
    bool? bot,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCredentials,
          [domain],
          {
            #displayName: displayName,
            #note: note,
            #avatar: avatar,
            #header: header,
            #locked: locked,
            #bot: bot,
          },
        ),
        returnValue: _i6.Future<_i2.Account>.value(_FakeAccount_0(
          this,
          Invocation.method(
            #updateCredentials,
            [domain],
            {
              #displayName: displayName,
              #note: note,
              #avatar: avatar,
              #header: header,
              #locked: locked,
              #bot: bot,
            },
          ),
        )),
      ) as _i6.Future<_i2.Account>);
}

/// A class which mocks [TimelineService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimelineService extends _i1.Mock implements _i7.TimelineService {
  MockTimelineService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i4.Status>> getHomeTimeline(
    String? domain, {
    int? limit,
    String? maxId,
    String? sinceId,
    String? minId,
    bool? local,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHomeTimeline,
          [domain],
          {
            #limit: limit,
            #maxId: maxId,
            #sinceId: sinceId,
            #minId: minId,
            #local: local,
          },
        ),
        returnValue: _i6.Future<List<_i4.Status>>.value(<_i4.Status>[]),
      ) as _i6.Future<List<_i4.Status>>);

  @override
  _i6.Future<List<_i4.Status>> getPublicTimeline(
    String? domain, {
    int? limit,
    String? maxId,
    String? sinceId,
    String? minId,
    bool? local,
    bool? remote,
    bool? onlyMedia,
    _i8.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPublicTimeline,
          [domain],
          {
            #limit: limit,
            #maxId: maxId,
            #sinceId: sinceId,
            #minId: minId,
            #local: local,
            #remote: remote,
            #onlyMedia: onlyMedia,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i6.Future<List<_i4.Status>>.value(<_i4.Status>[]),
      ) as _i6.Future<List<_i4.Status>>);

  @override
  _i6.Future<List<_i4.Status>> getTagTimeline(
    String? domain,
    String? tag, {
    int? limit,
    String? maxId,
    String? sinceId,
    String? minId,
    bool? local,
    bool? onlyMedia,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTagTimeline,
          [
            domain,
            tag,
          ],
          {
            #limit: limit,
            #maxId: maxId,
            #sinceId: sinceId,
            #minId: minId,
            #local: local,
            #onlyMedia: onlyMedia,
          },
        ),
        returnValue: _i6.Future<List<_i4.Status>>.value(<_i4.Status>[]),
      ) as _i6.Future<List<_i4.Status>>);

  @override
  _i6.Future<List<_i4.Status>> getListTimeline(
    String? domain,
    String? listId, {
    int? limit,
    String? maxId,
    String? sinceId,
    String? minId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListTimeline,
          [
            domain,
            listId,
          ],
          {
            #limit: limit,
            #maxId: maxId,
            #sinceId: sinceId,
            #minId: minId,
          },
        ),
        returnValue: _i6.Future<List<_i4.Status>>.value(<_i4.Status>[]),
      ) as _i6.Future<List<_i4.Status>>);

  @override
  _i6.Future<List<_i4.Status>> getAccountStatuses(
    String? domain,
    String? accountId, {
    int? limit,
    String? maxId,
    String? sinceId,
    String? minId,
    int? offset,
    bool? onlyMedia,
    bool? excludeReplies,
    bool? excludeReblogs,
    bool? pinned,
    _i8.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountStatuses,
          [
            domain,
            accountId,
          ],
          {
            #limit: limit,
            #maxId: maxId,
            #sinceId: sinceId,
            #minId: minId,
            #offset: offset,
            #onlyMedia: onlyMedia,
            #excludeReplies: excludeReplies,
            #excludeReblogs: excludeReblogs,
            #pinned: pinned,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i6.Future<List<_i4.Status>>.value(<_i4.Status>[]),
      ) as _i6.Future<List<_i4.Status>>);

  @override
  _i6.Future<List<_i4.Status>> getFavourites(
    String? domain, {
    int? limit,
    String? maxId,
    _i8.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavourites,
          [domain],
          {
            #limit: limit,
            #maxId: maxId,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i6.Future<List<_i4.Status>>.value(<_i4.Status>[]),
      ) as _i6.Future<List<_i4.Status>>);

  @override
  _i6.Future<List<_i4.Status>> getBookmarks(
    String? domain, {
    int? limit,
    String? maxId,
    _i8.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookmarks,
          [domain],
          {
            #limit: limit,
            #maxId: maxId,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i6.Future<List<_i4.Status>>.value(<_i4.Status>[]),
      ) as _i6.Future<List<_i4.Status>>);

  @override
  _i6.Future<List<_i4.Status>> getTrendingStatuses(
    String? domain, {
    int? limit,
    _i8.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrendingStatuses,
          [domain],
          {
            #limit: limit,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i6.Future<List<_i4.Status>>.value(<_i4.Status>[]),
      ) as _i6.Future<List<_i4.Status>>);

  @override
  _i6.Future<_i4.Status> getStatus(
    String? domain,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStatus,
          [
            domain,
            id,
          ],
        ),
        returnValue: _i6.Future<_i4.Status>.value(_FakeStatus_2(
          this,
          Invocation.method(
            #getStatus,
            [
              domain,
              id,
            ],
          ),
        )),
      ) as _i6.Future<_i4.Status>);

  @override
  _i6.Future<Map<String, List<_i4.Status>>> getStatusContext(
    String? domain,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStatusContext,
          [
            domain,
            id,
          ],
        ),
        returnValue: _i6.Future<Map<String, List<_i4.Status>>>.value(
            <String, List<_i4.Status>>{}),
      ) as _i6.Future<Map<String, List<_i4.Status>>>);

  @override
  _i6.Future<_i4.Status> createStatus(
    String? domain, {
    required String? status,
    String? inReplyToId,
    List<String>? mediaIds,
    bool? sensitive,
    String? spoilerText,
    _i4.Visibility? visibility,
    String? scheduledAt,
    String? language,
    Map<String, dynamic>? poll,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStatus,
          [domain],
          {
            #status: status,
            #inReplyToId: inReplyToId,
            #mediaIds: mediaIds,
            #sensitive: sensitive,
            #spoilerText: spoilerText,
            #visibility: visibility,
            #scheduledAt: scheduledAt,
            #language: language,
            #poll: poll,
          },
        ),
        returnValue: _i6.Future<_i4.Status>.value(_FakeStatus_2(
          this,
          Invocation.method(
            #createStatus,
            [domain],
            {
              #status: status,
              #inReplyToId: inReplyToId,
              #mediaIds: mediaIds,
              #sensitive: sensitive,
              #spoilerText: spoilerText,
              #visibility: visibility,
              #scheduledAt: scheduledAt,
              #language: language,
              #poll: poll,
            },
          ),
        )),
      ) as _i6.Future<_i4.Status>);

  @override
  _i6.Future<void> deleteStatus(
    String? domain,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteStatus,
          [
            domain,
            id,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.Status> reblogStatus(
    String? domain,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reblogStatus,
          [
            domain,
            id,
          ],
        ),
        returnValue: _i6.Future<_i4.Status>.value(_FakeStatus_2(
          this,
          Invocation.method(
            #reblogStatus,
            [
              domain,
              id,
            ],
          ),
        )),
      ) as _i6.Future<_i4.Status>);

  @override
  _i6.Future<_i4.Status> unreblogStatus(
    String? domain,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unreblogStatus,
          [
            domain,
            id,
          ],
        ),
        returnValue: _i6.Future<_i4.Status>.value(_FakeStatus_2(
          this,
          Invocation.method(
            #unreblogStatus,
            [
              domain,
              id,
            ],
          ),
        )),
      ) as _i6.Future<_i4.Status>);

  @override
  _i6.Future<_i4.Status> favouriteStatus(
    String? domain,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #favouriteStatus,
          [
            domain,
            id,
          ],
        ),
        returnValue: _i6.Future<_i4.Status>.value(_FakeStatus_2(
          this,
          Invocation.method(
            #favouriteStatus,
            [
              domain,
              id,
            ],
          ),
        )),
      ) as _i6.Future<_i4.Status>);

  @override
  _i6.Future<_i4.Status> unfavouriteStatus(
    String? domain,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unfavouriteStatus,
          [
            domain,
            id,
          ],
        ),
        returnValue: _i6.Future<_i4.Status>.value(_FakeStatus_2(
          this,
          Invocation.method(
            #unfavouriteStatus,
            [
              domain,
              id,
            ],
          ),
        )),
      ) as _i6.Future<_i4.Status>);

  @override
  _i6.Future<List<_i2.Account>> getStatusRebloggedBy(
    String? domain,
    String? id, {
    int? limit,
    String? maxId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStatusRebloggedBy,
          [
            domain,
            id,
          ],
          {
            #limit: limit,
            #maxId: maxId,
          },
        ),
        returnValue: _i6.Future<List<_i2.Account>>.value(<_i2.Account>[]),
      ) as _i6.Future<List<_i2.Account>>);

  @override
  _i6.Future<List<_i2.Account>> getStatusFavouritedBy(
    String? domain,
    String? id, {
    int? limit,
    String? maxId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStatusFavouritedBy,
          [
            domain,
            id,
          ],
          {
            #limit: limit,
            #maxId: maxId,
          },
        ),
        returnValue: _i6.Future<List<_i2.Account>>.value(<_i2.Account>[]),
      ) as _i6.Future<List<_i2.Account>>);

  @override
  _i6.Future<_i4.Status> bookmarkStatus(
    String? domain,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #bookmarkStatus,
          [
            domain,
            id,
          ],
        ),
        returnValue: _i6.Future<_i4.Status>.value(_FakeStatus_2(
          this,
          Invocation.method(
            #bookmarkStatus,
            [
              domain,
              id,
            ],
          ),
        )),
      ) as _i6.Future<_i4.Status>);

  @override
  _i6.Future<_i4.Status> unbookmarkStatus(
    String? domain,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unbookmarkStatus,
          [
            domain,
            id,
          ],
        ),
        returnValue: _i6.Future<_i4.Status>.value(_FakeStatus_2(
          this,
          Invocation.method(
            #unbookmarkStatus,
            [
              domain,
              id,
            ],
          ),
        )),
      ) as _i6.Future<_i4.Status>);

  @override
  _i6.Future<_i4.Status> pinStatus(
    String? domain,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #pinStatus,
          [
            domain,
            id,
          ],
        ),
        returnValue: _i6.Future<_i4.Status>.value(_FakeStatus_2(
          this,
          Invocation.method(
            #pinStatus,
            [
              domain,
              id,
            ],
          ),
        )),
      ) as _i6.Future<_i4.Status>);

  @override
  _i6.Future<_i4.Status> unpinStatus(
    String? domain,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unpinStatus,
          [
            domain,
            id,
          ],
        ),
        returnValue: _i6.Future<_i4.Status>.value(_FakeStatus_2(
          this,
          Invocation.method(
            #unpinStatus,
            [
              domain,
              id,
            ],
          ),
        )),
      ) as _i6.Future<_i4.Status>);
}
