// Mocks generated by Mockito 5.4.4 from annotations
// in pixelodon/test/providers/auth_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pixelodon/models/account.dart' as _i5;
import 'package:pixelodon/models/instance.dart' as _i2;
import 'package:pixelodon/services/auth_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeInstance_0 extends _i1.SmartFake implements _i2.Instance {
  _FakeInstance_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i3.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Instance> discoverInstance(String? domain) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverInstance,
          [domain],
        ),
        returnValue: _i4.Future<_i2.Instance>.value(_FakeInstance_0(
          this,
          Invocation.method(
            #discoverInstance,
            [domain],
          ),
        )),
      ) as _i4.Future<_i2.Instance>);

  @override
  _i4.Future<Map<String, String>> getClientCredentials(String? domain) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClientCredentials,
          [domain],
        ),
        returnValue: _i4.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i4.Future<Map<String, String>>);

  @override
  _i4.Future<Map<String, String>> getAuthorizationUrl(
    String? domain, {
    bool? forRegistration = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAuthorizationUrl,
          [domain],
          {#forRegistration: forRegistration},
        ),
        returnValue: _i4.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i4.Future<Map<String, String>>);

  @override
  _i4.Future<Map<String, String>> exchangeAuthorizationCode(
    String? domain,
    String? code, {
    String? state,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exchangeAuthorizationCode,
          [
            domain,
            code,
          ],
          {#state: state},
        ),
        returnValue: _i4.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i4.Future<Map<String, String>>);

  @override
  _i4.Future<Map<String, String>> refreshAccessToken(String? domain) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshAccessToken,
          [domain],
        ),
        returnValue: _i4.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i4.Future<Map<String, String>>);

  @override
  _i4.Future<String?> getAccessToken(String? domain) => (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [domain],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<String?> getRefreshToken(String? domain) => (super.noSuchMethod(
        Invocation.method(
          #getRefreshToken,
          [domain],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<_i5.Account?> getAccountInfo(String? domain) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountInfo,
          [domain],
        ),
        returnValue: _i4.Future<_i5.Account?>.value(),
      ) as _i4.Future<_i5.Account?>);

  @override
  _i4.Future<bool> isAuthenticated(String? domain) => (super.noSuchMethod(
        Invocation.method(
          #isAuthenticated,
          [domain],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<String>> getAuthenticatedInstances() => (super.noSuchMethod(
        Invocation.method(
          #getAuthenticatedInstances,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<void> logout(String? domain) => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [domain],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> validateAccessToken(
    String? domain,
    String? accessToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateAccessToken,
          [
            domain,
            accessToken,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
