import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:pixelodon/models/account.dart';
import 'package:pixelodon/models/instance.dart';
import 'package:pixelodon/repositories/auth_repository.dart';
import 'package:pixelodon/services/auth_service.dart';

part 'auth_provider.g.dart';

/// Provider for the AuthService
@Riverpod(keepAlive: true)
AuthService authService(AuthServiceRef ref) {
  return AuthService();
}

// NOTE: authRepositoryProvider is now generated by @riverpod in auth_repository.dart
// We don't define it here to avoid conflicts.

/// Provider for the list of authenticated instances
@Riverpod(keepAlive: true)
List<Instance> instances(InstancesRef ref) {
  final state = ref.watch(authRepositoryProvider);
  return state.instances;
}

/// Provider for the currently active instance
@Riverpod(keepAlive: true)
Instance? activeInstance(ActiveInstanceRef ref) {
  final state = ref.watch(authRepositoryProvider);
  return state.activeInstance;
}

/// Provider for the currently active account
@Riverpod(keepAlive: true)
Account? activeAccount(ActiveAccountRef ref) {
  final state = ref.watch(authRepositoryProvider);
  return state.activeAccount;
}

/// Provider for checking if a user is authenticated with a specific instance
@Riverpod(keepAlive: true)
Future<bool> isAuthenticated(IsAuthenticatedRef ref, String domain) async {
  final notifier = ref.watch(authRepositoryProvider.notifier);
  return notifier.isAuthenticated(domain);
}

/// Provider for getting the access token for a specific instance
@Riverpod(keepAlive: true)
Future<String?> accessToken(AccessTokenRef ref, String domain) async {
  final notifier = ref.watch(authRepositoryProvider.notifier);
  return notifier.getAccessToken(domain);
}

/// Provider for validating an access token for a specific instance
@Riverpod(keepAlive: true)
Future<bool> validateAccessToken(ValidateAccessTokenRef ref, String domain) async {
  final notifier = ref.watch(authRepositoryProvider.notifier);
  return notifier.validateAccessToken(domain);
}

/// Provider for discovering an instance by domain
@Riverpod(keepAlive: true)
Future<Instance> instanceDiscovery(InstanceDiscoveryRef ref, String domain) async {
  final notifier = ref.watch(authRepositoryProvider.notifier);
  return notifier.discoverInstance(domain);
}

/// Provider for starting the OAuth flow
@Riverpod(keepAlive: true)
Future<Map<String, String>> oauthFlow(OauthFlowRef ref, String domain) async {
  final notifier = ref.watch(authRepositoryProvider.notifier);
  return notifier.startOAuthFlow(domain);
}

/// Provider for completing the OAuth flow
@Riverpod(keepAlive: true)
Future<bool> completeOAuthFlow(CompleteOAuthFlowRef ref, ({String domain, String code, String? state}) params) async {
  final notifier = ref.watch(authRepositoryProvider.notifier);
  return notifier.completeOAuthFlow(params.domain, params.code, state: params.state);
}

/// Provider for refreshing an access token
@Riverpod(keepAlive: true)
Future<bool> refreshAccessToken(RefreshAccessTokenRef ref, String domain) async {
  final notifier = ref.watch(authRepositoryProvider.notifier);
  return notifier.refreshAccessToken(domain);
}

/// Provider for getting account information for a domain
@Riverpod(keepAlive: true)
Account? accountInfo(AccountInfoRef ref, String domain) {
  final state = ref.watch(authRepositoryProvider);
  return state.accounts[domain];
}

/// Provider for updating account information for a domain
@Riverpod(keepAlive: true)
Future<void> updateAccountInfo(UpdateAccountInfoRef ref, String domain) async {
  final notifier = ref.watch(authRepositoryProvider.notifier);
  await notifier.updateAccountInfo(domain);
}
