// Mocks generated by Mockito 5.4.4 from annotations
// in pixelodon/test/test_support/network_stubs.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pixelodon/models/status.dart' as _i2;
import 'package:pixelodon/services/timeline_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStatus_0 extends _i1.SmartFake implements _i2.Status {
  _FakeStatus_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TimelineService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimelineService extends _i1.Mock implements _i3.TimelineService {
  MockTimelineService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Status>> getHomeTimeline(
    String? domain, {
    int? limit,
    String? maxId,
    String? sinceId,
    String? minId,
    bool? local,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHomeTimeline,
          [domain],
          {
            #limit: limit,
            #maxId: maxId,
            #sinceId: sinceId,
            #minId: minId,
            #local: local,
          },
        ),
        returnValue: _i4.Future<List<_i2.Status>>.value(<_i2.Status>[]),
      ) as _i4.Future<List<_i2.Status>>);

  @override
  _i4.Future<List<_i2.Status>> getPublicTimeline(
    String? domain, {
    int? limit,
    String? maxId,
    String? sinceId,
    String? minId,
    bool? local,
    bool? remote,
    bool? onlyMedia,
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPublicTimeline,
          [domain],
          {
            #limit: limit,
            #maxId: maxId,
            #sinceId: sinceId,
            #minId: minId,
            #local: local,
            #remote: remote,
            #onlyMedia: onlyMedia,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i4.Future<List<_i2.Status>>.value(<_i2.Status>[]),
      ) as _i4.Future<List<_i2.Status>>);

  @override
  _i4.Future<List<_i2.Status>> getTagTimeline(
    String? domain,
    String? tag, {
    int? limit,
    String? maxId,
    String? sinceId,
    String? minId,
    bool? local,
    bool? onlyMedia,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTagTimeline,
          [
            domain,
            tag,
          ],
          {
            #limit: limit,
            #maxId: maxId,
            #sinceId: sinceId,
            #minId: minId,
            #local: local,
            #onlyMedia: onlyMedia,
          },
        ),
        returnValue: _i4.Future<List<_i2.Status>>.value(<_i2.Status>[]),
      ) as _i4.Future<List<_i2.Status>>);

  @override
  _i4.Future<List<_i2.Status>> getListTimeline(
    String? domain,
    String? listId, {
    int? limit,
    String? maxId,
    String? sinceId,
    String? minId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListTimeline,
          [
            domain,
            listId,
          ],
          {
            #limit: limit,
            #maxId: maxId,
            #sinceId: sinceId,
            #minId: minId,
          },
        ),
        returnValue: _i4.Future<List<_i2.Status>>.value(<_i2.Status>[]),
      ) as _i4.Future<List<_i2.Status>>);

  @override
  _i4.Future<List<_i2.Status>> getAccountStatuses(
    String? domain,
    String? accountId, {
    int? limit,
    String? maxId,
    String? sinceId,
    String? minId,
    int? offset,
    bool? onlyMedia,
    bool? excludeReplies,
    bool? excludeReblogs,
    bool? pinned,
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountStatuses,
          [
            domain,
            accountId,
          ],
          {
            #limit: limit,
            #maxId: maxId,
            #sinceId: sinceId,
            #minId: minId,
            #offset: offset,
            #onlyMedia: onlyMedia,
            #excludeReplies: excludeReplies,
            #excludeReblogs: excludeReblogs,
            #pinned: pinned,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i4.Future<List<_i2.Status>>.value(<_i2.Status>[]),
      ) as _i4.Future<List<_i2.Status>>);

  @override
  _i4.Future<List<_i2.Status>> getFavourites(
    String? domain, {
    int? limit,
    String? maxId,
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavourites,
          [domain],
          {
            #limit: limit,
            #maxId: maxId,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i4.Future<List<_i2.Status>>.value(<_i2.Status>[]),
      ) as _i4.Future<List<_i2.Status>>);

  @override
  _i4.Future<List<_i2.Status>> getBookmarks(
    String? domain, {
    int? limit,
    String? maxId,
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookmarks,
          [domain],
          {
            #limit: limit,
            #maxId: maxId,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i4.Future<List<_i2.Status>>.value(<_i2.Status>[]),
      ) as _i4.Future<List<_i2.Status>>);

  @override
  _i4.Future<List<_i2.Status>> getTrendingStatuses(
    String? domain, {
    int? limit,
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrendingStatuses,
          [domain],
          {
            #limit: limit,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i4.Future<List<_i2.Status>>.value(<_i2.Status>[]),
      ) as _i4.Future<List<_i2.Status>>);

  @override
  _i4.Future<_i2.Status> getStatus(
    String? domain,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStatus,
          [
            domain,
            id,
          ],
        ),
        returnValue: _i4.Future<_i2.Status>.value(_FakeStatus_0(
          this,
          Invocation.method(
            #getStatus,
            [
              domain,
              id,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Status>);

  @override
  _i4.Future<Map<String, List<_i2.Status>>> getStatusContext(
    String? domain,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStatusContext,
          [
            domain,
            id,
          ],
        ),
        returnValue: _i4.Future<Map<String, List<_i2.Status>>>.value(
            <String, List<_i2.Status>>{}),
      ) as _i4.Future<Map<String, List<_i2.Status>>>);

  @override
  _i4.Future<_i2.Status> createStatus(
    String? domain, {
    required String? status,
    String? inReplyToId,
    List<String>? mediaIds,
    bool? sensitive,
    String? spoilerText,
    _i2.Visibility? visibility,
    String? scheduledAt,
    String? language,
    Map<String, dynamic>? poll,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStatus,
          [domain],
          {
            #status: status,
            #inReplyToId: inReplyToId,
            #mediaIds: mediaIds,
            #sensitive: sensitive,
            #spoilerText: spoilerText,
            #visibility: visibility,
            #scheduledAt: scheduledAt,
            #language: language,
            #poll: poll,
          },
        ),
        returnValue: _i4.Future<_i2.Status>.value(_FakeStatus_0(
          this,
          Invocation.method(
            #createStatus,
            [domain],
            {
              #status: status,
              #inReplyToId: inReplyToId,
              #mediaIds: mediaIds,
              #sensitive: sensitive,
              #spoilerText: spoilerText,
              #visibility: visibility,
              #scheduledAt: scheduledAt,
              #language: language,
              #poll: poll,
            },
          ),
        )),
      ) as _i4.Future<_i2.Status>);

  @override
  _i4.Future<void> deleteStatus(
    String? domain,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteStatus,
          [
            domain,
            id,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.Status> reblogStatus(
    String? domain,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reblogStatus,
          [
            domain,
            id,
          ],
        ),
        returnValue: _i4.Future<_i2.Status>.value(_FakeStatus_0(
          this,
          Invocation.method(
            #reblogStatus,
            [
              domain,
              id,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Status>);

  @override
  _i4.Future<_i2.Status> unreblogStatus(
    String? domain,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unreblogStatus,
          [
            domain,
            id,
          ],
        ),
        returnValue: _i4.Future<_i2.Status>.value(_FakeStatus_0(
          this,
          Invocation.method(
            #unreblogStatus,
            [
              domain,
              id,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Status>);

  @override
  _i4.Future<_i2.Status> favouriteStatus(
    String? domain,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #favouriteStatus,
          [
            domain,
            id,
          ],
        ),
        returnValue: _i4.Future<_i2.Status>.value(_FakeStatus_0(
          this,
          Invocation.method(
            #favouriteStatus,
            [
              domain,
              id,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Status>);

  @override
  _i4.Future<_i2.Status> unfavouriteStatus(
    String? domain,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unfavouriteStatus,
          [
            domain,
            id,
          ],
        ),
        returnValue: _i4.Future<_i2.Status>.value(_FakeStatus_0(
          this,
          Invocation.method(
            #unfavouriteStatus,
            [
              domain,
              id,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Status>);

  @override
  _i4.Future<_i2.Status> bookmarkStatus(
    String? domain,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #bookmarkStatus,
          [
            domain,
            id,
          ],
        ),
        returnValue: _i4.Future<_i2.Status>.value(_FakeStatus_0(
          this,
          Invocation.method(
            #bookmarkStatus,
            [
              domain,
              id,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Status>);

  @override
  _i4.Future<_i2.Status> unbookmarkStatus(
    String? domain,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unbookmarkStatus,
          [
            domain,
            id,
          ],
        ),
        returnValue: _i4.Future<_i2.Status>.value(_FakeStatus_0(
          this,
          Invocation.method(
            #unbookmarkStatus,
            [
              domain,
              id,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Status>);

  @override
  _i4.Future<_i2.Status> pinStatus(
    String? domain,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #pinStatus,
          [
            domain,
            id,
          ],
        ),
        returnValue: _i4.Future<_i2.Status>.value(_FakeStatus_0(
          this,
          Invocation.method(
            #pinStatus,
            [
              domain,
              id,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Status>);

  @override
  _i4.Future<_i2.Status> unpinStatus(
    String? domain,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unpinStatus,
          [
            domain,
            id,
          ],
        ),
        returnValue: _i4.Future<_i2.Status>.value(_FakeStatus_0(
          this,
          Invocation.method(
            #unpinStatus,
            [
              domain,
              id,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Status>);
}
