// Mocks generated by Mockito 5.4.4 from annotations
// in pixelodon/test/features/onboarding/data/recommendation_engine_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pixelodon/features/onboarding/domain/instance_caps.dart' as _i2;
import 'package:pixelodon/infra/api/discovery/discovery_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeInstanceCaps_0 extends _i1.SmartFake implements _i2.InstanceCaps {
  _FakeInstanceCaps_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DiscoveryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiscoveryRepository extends _i1.Mock
    implements _i3.DiscoveryRepository {
  MockDiscoveryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.InstanceCaps> discoverInstance(String? domain) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverInstance,
          [domain],
        ),
        returnValue: _i4.Future<_i2.InstanceCaps>.value(_FakeInstanceCaps_0(
          this,
          Invocation.method(
            #discoverInstance,
            [domain],
          ),
        )),
      ) as _i4.Future<_i2.InstanceCaps>);

  @override
  _i4.Future<bool> validateDomain(String? domain) => (super.noSuchMethod(
        Invocation.method(
          #validateDomain,
          [domain],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
